# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generic_event.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'generic_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13generic_event.proto\x12\x11\x66\x65s.common.events\"\xd3\x01\n\x13GenericEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65vent_type_key\x18\x02 \x01(\t\x12\x15\n\revent_payload\x18\x03 \x01(\x0c\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x03\x12\x18\n\x10source_worker_id\x18\x05 \x01(\t\x12\x15\n\rsimulation_id\x18\x06 \x01(\t\x12\x1c\n\x14payload_content_type\x18\x07 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERICEVENTREQUEST']._serialized_start=43
  _globals['_GENERICEVENTREQUEST']._serialized_end=254
# @@protoc_insertion_point(module_scope)
