# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_comms.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'agent_comms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61gent_comms.proto\x12\x14\x66\x65s.simulation.agent\"\x82\x02\n\x07Percept\x12=\n\x0b\x65ntity_type\x18\x01 \x01(\x0e\x32(.fes.simulation.agent.Percept.EntityType\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x16\n\x0erelative_pos_x\x18\x03 \x01(\x02\x12\x16\n\x0erelative_pos_y\x18\x04 \x01(\x02\"u\n\nEntityType\x12\x1b\n\x17\x45NTITY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10\x45NTITY_TYPE_FOOD\x10\x01\x12\x15\n\x11\x45NTITY_TYPE_AGENT\x10\x02\x12\x1d\n\x19\x45NTITY_TYPE_WALL_OBSTACLE\x10\x03\"\xc6\x01\n\x10\x41gentObservation\x12\x16\n\x0e\x63urrent_energy\x18\x01 \x01(\x02\x12\x19\n\x11\x63urrent_age_ticks\x18\x02 \x01(\x03\x12\r\n\x05pos_x\x18\x03 \x01(\x02\x12\r\n\x05pos_y\x18\x04 \x01(\x02\x12\x1b\n\x13orientation_degrees\x18\x05 \x01(\x02\x12/\n\x08percepts\x18\x06 \x03(\x0b\x32\x1d.fes.simulation.agent.Percept\x12\x13\n\x0blast_reward\x18\x07 \x01(\x02\"R\n\x0b\x41gentAction\x12\x12\n\nmove_delta\x18\x01 \x01(\x02\x12\x1a\n\x12turn_delta_degrees\x18\x02 \x01(\x02\x12\x13\n\x0b\x61ttempt_eat\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_comms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERCEPT']._serialized_start=44
  _globals['_PERCEPT']._serialized_end=302
  _globals['_PERCEPT_ENTITYTYPE']._serialized_start=185
  _globals['_PERCEPT_ENTITYTYPE']._serialized_end=302
  _globals['_AGENTOBSERVATION']._serialized_start=305
  _globals['_AGENTOBSERVATION']._serialized_end=503
  _globals['_AGENTACTION']._serialized_start=505
  _globals['_AGENTACTION']._serialized_end=587
# @@protoc_insertion_point(module_scope)
