// @generated
// This file is @generated by prost-build.
/// GenericEventRequest serves as a common wrapper for various events
/// transmitted within the Fish Eco Sim system.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenericEventRequest {
    /// Unique identifier for this specific event instance (e.g., a UUID string).
    #[prost(string, tag="1")]
    pub event_id: ::prost::alloc::string::String,
    /// A key string identifying the type of event contained in the event_payload.
    /// Examples: "agent.spawn", "world.tick", "simulation.ended".
    #[prost(string, tag="2")]
    pub event_type_key: ::prost::alloc::string::String,
    /// The serialized payload of the specific event. The format is indicated
    /// by payload_content_type and implicitly by event_type_key.
    #[prost(bytes="vec", tag="3")]
    pub event_payload: ::prost::alloc::vec::Vec<u8>,
    /// UTC timestamp of when the event occurred or was generated,
    /// represented as nanoseconds since the Unix epoch.
    #[prost(int64, tag="4")]
    pub timestamp_ns: i64,
    /// Identifier of the service, worker, or component that originated this event.
    /// Examples: "sim-worker-01", "orchestrator", "ui-client-userX".
    #[prost(string, tag="5")]
    pub source_worker_id: ::prost::alloc::string::String,
    /// Identifier for the specific simulation run this event pertains to.
    /// Can be empty if the event is not specific to a simulation run.
    #[prost(string, tag="6")]
    pub simulation_id: ::prost::alloc::string::String,
    /// Describes the format and type of the event_payload.
    /// Helps consumers correctly deserialize the event_payload.
    /// Examples: "application/protobuf; message=fes.simulation.AgentSpawnedEvent",
    ///            "application/json",
    ///            "application/vnd.google.flatbuffers; type=WorldStateSnapshot"
    #[prost(string, tag="7")]
    pub payload_content_type: ::prost::alloc::string::String,
    /// Optional identifier used to correlate this event with other events or requests
    /// in a larger workflow or conversation. Can be empty if not applicable.
    #[prost(string, tag="8")]
    pub correlation_id: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
